name: dl-examples
channels:
- defaults
dependencies:
- python=3.6.2
- jupyter=1.0.0
- keras=2.0.5
- matplotlib=2.0.2
- numpy=1.13.1
- pillow=4.2.1
- scikit-learn=0.19.0
- tensorflow-gpu=1.3.0
- tqdm=4.15.0
